# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    build: .
    command: -c config_file=/etc/postgresql.conf
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./postgres.conf:/etc/postgresql.conf
    environment:
      POSTGRES_PASSWORD: my_super_secret
      POSTGRES_USER: ships